name: Linux Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-and-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run package build
      run: |
        make package

    - name: Upload Release Asset
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      with:
        files: turbostage-linux-${{ github.ref_name }}.zip
