name: Create Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run package build
      run: |
        make package

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: turbostage-linux-${{ github.ref_name }}.zip


  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run package build
      run: |
        poetry-dynamic-versioning
        pyinstaller --onefile --add-data "turbostage/content/splash.jpg:turbostage/content" -n turbostage turbostage/main.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/turbostage.exe
