name: Windows Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:

    runs-on: windows-latest

    permissions:
      contents: write
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run package build
      run: |
        poetry-dynamic-versioning
        pyinstaller --onefile --windowed --icon=turbostage/content/icon.ico --add-data "turbostage/content/splash.jpg:turbostage/content" -n turbostage turbostage/main.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      with:
        files: dist/turbostage.exe
